name: design_system_module
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^8.0.5
